"""upsert global alias

Revision ID: 0cde04133f8e
Revises: 047ec9ee8667
Create Date: 2025-11-28 16:20:52.349575

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cde04133f8e"
down_revision: Union[str, None] = "047ec9ee8667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "global_aliases" not in tables:
        op.create_table(
            "global_aliases",
            sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("alias_normalized", sa.Text(), nullable=False),
            sa.Column(
                "owning_tenant_id", postgresql.UUID(as_uuid=True), nullable=False
            ),
            sa.Column("routing_code", sa.String(length=11), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(
                ["owning_tenant_id"],
                ["tenants.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            "idx_global_alias_active",
            "global_aliases",
            ["alias_normalized", "is_active"],
            unique=False,
        )
        op.create_index(
            "idx_global_alias_normalized",
            "global_aliases",
            ["alias_normalized"],
            unique=True,
        )
        op.create_index(
            op.f("ix_global_aliases_created_at"),
            "global_aliases",
            ["created_at"],
            unique=False,
        )
        op.create_index(
            op.f("ix_global_aliases_id"), "global_aliases", ["id"], unique=False
        )
        op.create_index(
            op.f("ix_global_aliases_owning_tenant_id"),
            "global_aliases",
            ["owning_tenant_id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "global_aliases" in tables:
        op.drop_index("idx_global_alias_normalized", table_name="global_aliases")
        op.drop_index("idx_global_alias_active", table_name="global_aliases")
        op.drop_index(
            op.f("ix_global_aliases_owning_tenant_id"), table_name="global_aliases"
        )
        op.drop_index(op.f("ix_global_aliases_id"), table_name="global_aliases")
        op.drop_index(op.f("ix_global_aliases_created_at"), table_name="global_aliases")
        op.drop_table("global_aliases")
    # ### end Alembic commands ###
