"""interop migration

Revision ID: 23f1f81ea498
Revises: ea91938dcd32
Create Date: 2025-11-27 00:10:37.804181

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23f1f81ea498"
down_revision: Union[str, None] = "ea91938dcd32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alias_events",
        "tenant_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        postgresql_using="tenant_id::uuid",
        existing_nullable=False,
    )
    op.alter_column(
        "alias_registries",
        "tenant_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        postgresql_using="tenant_id::uuid",
        existing_nullable=False,
    )

    # CREAR LA TABLA interop_audits COMPLETA
    op.create_table(
        "interop_audits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("requesting_tenant_id", sa.UUID(), nullable=False),
        sa.Column("alias_normalized", sa.Text(), nullable=False),
        sa.Column("target_tenant_id", sa.UUID(), nullable=True),
        sa.Column(
            "query_type",
            postgresql.ENUM(
                "GLOBAL_VALIDATION",
                "CROSS_TENANT_LOOKUP",
                "ROUTING_RESOLUTION",
                "COMPLIANCE_CHECK",
                "FRAUD_VALIDATION",
                name="equerytype",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Crear los índices
    op.create_index(
        "ix_interop_audits_requesting_tenant_id",
        "interop_audits",
        ["requesting_tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_interop_audits_target_tenant_id",
        "interop_audits",
        ["target_tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_interop_audits_query_type", "interop_audits", ["query_type"], unique=False
    )
    op.create_index(
        "ix_interop_audits_timestamp", "interop_audits", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_interop_audits_correlation_id",
        "interop_audits",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        "idx_interop_alias_tenant",
        "interop_audits",
        ["alias_normalized", "requesting_tenant_id"],
        unique=False,
    )
    op.create_index(
        "idx_interop_timestamp", "interop_audits", ["timestamp"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar índices primero
    op.drop_index("idx_interop_timestamp", table_name="interop_audits")
    op.drop_index("idx_interop_alias_tenant", table_name="interop_audits")
    op.drop_index("ix_interop_audits_correlation_id", table_name="interop_audits")
    op.drop_index("ix_interop_audits_timestamp", table_name="interop_audits")
    op.drop_index("ix_interop_audits_query_type", table_name="interop_audits")
    op.drop_index("ix_interop_audits_target_tenant_id", table_name="interop_audits")
    op.drop_index("ix_interop_audits_requesting_tenant_id", table_name="interop_audits")

    # Eliminar la tabla
    op.drop_table("interop_audits")

    # Eliminar el tipo ENUM si es necesario
    op.execute("DROP TYPE IF EXISTS equerytype")

    op.alter_column(
        "alias_registries",
        "tenant_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "alias_events",
        "tenant_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
