"""first migration

Revision ID: 5e0028d653fa
Revises: 
Create Date: 2025-11-18 19:19:45.716563

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e0028d653fa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN CREATE TYPE alias_status AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )

    op.create_table(
        "alias_events",
        sa.Column("alias_normalized", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("current_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alias_events_alias_normalized"),
        "alias_events",
        ["alias_normalized"],
        unique=False,
    )
    op.create_index(op.f("ix_alias_events_id"), "alias_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_alias_events_tenant_id"), "alias_events", ["tenant_id"], unique=False
    )

    op.execute(
        """
    CREATE TABLE IF NOT EXISTS alias_registries (
        id UUID PRIMARY KEY,
        tenant_id VARCHAR(255) NOT NULL,
        alias_raw TEXT NOT NULL,
        alias_normalized TEXT NOT NULL,
        bank VARCHAR(255) NOT NULL,
        account_type VARCHAR(255) NOT NULL,
        last_4 VARCHAR(4) NOT NULL,
        status alias_status NOT NULL,
        acc_hash VARCHAR(255),
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ,
        deleted_at TIMESTAMPTZ
    )
    """
    )

    op.create_index(
        "idx_alias_tenant_active",
        "alias_registries",
        ["alias_normalized", "tenant_id", "status"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        op.f("ix_alias_registries_alias_normalized"),
        "alias_registries",
        ["alias_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alias_registries_id"), "alias_registries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_alias_registries_tenant_id"),
        "alias_registries",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "banners",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_banners_id"), "banners", ["id"], unique=False)
    op.create_index(
        op.f("ix_banners_is_active"), "banners", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_banners_title"), "banners", ["title"], unique=False)
    op.create_table(
        "error_logs",
        sa.Column("error_type", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_error_logs_id"), "error_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_error_logs_id"), table_name="error_logs")
    op.drop_table("error_logs")
    op.drop_index(op.f("ix_banners_title"), table_name="banners")
    op.drop_index(op.f("ix_banners_is_active"), table_name="banners")
    op.drop_index(op.f("ix_banners_id"), table_name="banners")
    op.drop_table("banners")
    op.drop_index(op.f("ix_alias_registries_tenant_id"), table_name="alias_registries")
    op.drop_index(op.f("ix_alias_registries_id"), table_name="alias_registries")
    op.drop_index(
        op.f("ix_alias_registries_alias_normalized"), table_name="alias_registries"
    )
    op.drop_index(
        "idx_alias_tenant_active",
        table_name="alias_registries",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("alias_registries")
    op.drop_index(op.f("ix_alias_events_tenant_id"), table_name="alias_events")
    op.drop_index(op.f("ix_alias_events_id"), table_name="alias_events")
    op.drop_index(op.f("ix_alias_events_alias_normalized"), table_name="alias_events")
    op.drop_table("alias_events")
    # ### end Alembic commands ###
