"""change event type to enum

Revision ID: 6fb6e4d1bc82
Revises: 7fd3dc613fd6
Create Date: 2025-11-20 22:48:59.573378

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fb6e4d1bc82"
down_revision: Union[str, None] = "7fd3dc613fd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    eeventtype = postgresql.ENUM("REGISTER", "RESOLVE", "DEACTIVATE", name="eeventtype")
    eeventtype.create(op.get_bind())

    op.alter_column(
        "alias_events",
        "event_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("REGISTER", "RESOLVE", "DEACTIVATE", name="eeventtype"),
        existing_nullable=False,
        postgresql_using="event_type::eeventtype",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alias_events",
        "event_type",
        existing_type=sa.Enum("REGISTER", "RESOLVE", "DEACTIVATE", name="eeventtype"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )

    eeventtype = postgresql.ENUM("REGISTER", "RESOLVE", "DEACTIVATE", name="eeventtype")
    eeventtype.drop(op.get_bind())
    # ### end Alembic commands ###
