"""change unique restriction at interop audit

Revision ID: 7c5214149b81
Revises: 23f1f81ea498
Create Date: 2025-11-27 14:23:30.628654

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "7c5214149b81"
down_revision: Union[str, None] = "23f1f81ea498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_interop_audit_unique', table_name='interop_audits')
    # op.create_index(
    #     "idx_interop_alias_tenant",
    #     "interop_audits",
    #     ["alias_normalized", "requesting_tenant_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     "idx_interop_timestamp", "interop_audits", ["timestamp"], unique=False
    # )
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index("idx_interop_timestamp", table_name="interop_audits")
    # op.drop_index("idx_interop_alias_tenant", table_name="interop_audits")
    # op.create_index(
    #     "idx_interop_audit_unique",
    #     "interop_audits",
    #     ["alias_normalized", "requesting_tenant_id", "target_tenant_id"],
    #     unique=True,
    # )
    # ### end Alembic commands ###
    pass
