"""improve tenant to admin

Revision ID: 7fd3dc613fd6
Revises: c797acdebdfb
Create Date: 2025-11-19 19:41:00.386884

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "7fd3dc613fd6"
down_revision: Union[str, None] = "c797acdebdfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
