"""tenant migration

Revision ID: c797acdebdfb
Revises: 5e0028d653fa
Create Date: 2025-11-19 00:27:09.179776

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c797acdebdfb"
down_revision: Union[str, None] = "5e0028d653fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "type",
            sa.Enum("BANK", "ADMIN", "PARTNER", name="tenanttype"),
            nullable=False,
        ),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("tax_id", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", "PENDING", name="tenantstatus"),
            nullable=False,
        ),
        sa.Column("tenant_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "roles",
            postgresql.ARRAY(sa.Enum("ADMIN", "OPERATOR", "VIEWER", name="tenantrole")),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_email"),
        sa.UniqueConstraint("tax_id"),
    )
    op.create_index(
        "idx_tenant_active_banks", "tenants", ["status", "type"], unique=False
    )
    op.create_index(
        "idx_tenant_status_type", "tenants", ["status", "type"], unique=False
    )
    op.create_index(op.f("ix_tenants_code"), "tenants", ["code"], unique=True)
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_code"), table_name="tenants")
    op.drop_index("idx_tenant_status_type", table_name="tenants")
    op.drop_index("idx_tenant_active_banks", table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
