"""change account type to enum

Revision ID: d50b0fcfae8b
Revises: 6fb6e4d1bc82
Create Date: 2025-11-20 22:54:59.628090

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d50b0fcfae8b"
down_revision: Union[str, None] = "6fb6e4d1bc82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    eaccounttype = postgresql.ENUM(
        "CTA_VISTA", "CTA_CORRIENTE", "CTA_AHORRO", "CTA_PLATINUM", name="account_type"
    )
    eaccounttype.create(op.get_bind())

    op.alter_column(
        "alias_registries",
        "account_type",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Enum(
            "CTA_VISTA",
            "CTA_CORRIENTE",
            "CTA_AHORRO",
            "CTA_PLATINUM",
            name="account_type",
        ),
        existing_nullable=False,
        postgresql_using="account_type::account_type",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alias_registries",
        "account_type",
        existing_type=sa.Enum(
            "CTA_VISTA",
            "CTA_CORRIENTE",
            "CTA_AHORRO",
            "CTA_PLATINUM",
            name="account_type",
        ),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )

    # ### end Alembic commands ###
