"""change enum for tenant

Revision ID: ea91938dcd32
Revises: d50b0fcfae8b
Create Date: 2025-11-24 22:59:56.984388

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "ea91938dcd32"
down_revision: Union[str, None] = "d50b0fcfae8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
